### ISSUE TITLE
Dont listed on service connection AZDEVOPS

### ISSUE THREAD

**Issue by rdaruich** [kiuwan/tfs-vsts-extension#22]
Hi,

before updated 2.3.35 i don't see on my listed service connection on project.

![image](https://user-images.githubusercontent.com/25388140/60738189-72350c00-9f2b-11e9-84f4-17940277fe8f.png)

**Comment by rdaruich** [comment]
4 days and no comments?

**Comment by luisgarciakiuwan** [comment]
Hi

Sorry not answering before., we have been really busy these days ....

I suppose you are using AzureDevops (please let me know if not). 

We have tested it and it works perfectly. 

The issue may come because depending on the bowser settings) , when you open the New Service Connection, the list seems to be finsihed but there's a "hidden" scroll that lets you see all the available list. Just click and when the mouse is in that window you will see the scroll and find the Kiuwan one. 

See the image:
![KWSvc](https://user-images.githubusercontent.com/51816696/60949220-040a9380-a2f5-11e9-87f2-954aab5d6334.JPG)

Let me know if this helps. 

Regards
Luis
