### ISSUE TITLE
Analysis result are different between local Analysis and VSTS Task with same configuration

### ISSUE THREAD

**Issue by DaniCCardenas** [kiuwan/tfs-vsts-extension#8]
Hi,
I am trying to automatize my proyect build and Kiuwan analysis. Before this I launched Kiuwan Local Analycer and I got a result. If I launch an analysis with same configuration from VSTS task I get different result. Different numbrer of files and lines of code analyzed and of course, different results.

![image](https://user-images.githubusercontent.com/22773251/43001544-dc31449e-8c25-11e8-9d60-865be8766f69.png)

I don't know why is analizing different number of files (exclude patterns was copied and pasted from local)

**Comment by jsalado** [comment]
Hello there,

You have to bear in mind that the source code directory the VSTS task uses to run the analysis is the VSTS agent's sources directory (that is basically the directory where the previous Get Sources step extract the code from the repository. 

Since with the KLA you have the liberty to specify the directory, you are most probably specifying a directory that is 1 or more level below the repository root, and that is why you are getting less files with the KLA you are leaving some files un-analyzed in the higher levels.

Go to your analysis results and check the signature of the file names, you will see if there are directories missing or not. Just make sure to run the KLA analysis again specifying the right application source directory.

**Comment by DaniCCardenas** [comment]
I can't find the place where I can see analyzed files and folders

**Comment by jsalado** [comment]
Hello again,

there are several ways to see the signature (path/filename) of the analyzed files (although you will only see the ones with defects/vulnerabilities). This depends on the products you have in your subscription.

If you have Code Security. You can go to the files tab and see a complete list of files with vulnerabilities. You will see that the path in the files signature will be different in the KLA analysis and the one from VSTS. That is because the root directory especified for the analysis is different as I explained in my previous comment. You can see files signature as well when you drill down in the vulnerabilities tab, for every vulnerability when you click on it you get the list of files where Kiuwan found it.

If you have Code Analysis. You can see the signature of the files drilling down in the defects screen clicking the each defect. Or in that same defect screen grouping the list by files (look for the combo in the filter bar to the right)

I hope this helps.

**Comment by DaniCCardenas** [comment]
I am going to check defects list to discover the difference between analysis.
Thanks!

**Comment by jsalado** [comment]
I'm glad you could figure it out.

Best,
J.
